# Generated by Django 4.1.5 on 2023-07-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='bannerImg',
            field=models.ImageField(null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='errorImg',
            field=models.ImageField(null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='homeBackgroundImg',
            field=models.ImageField(null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logoIcon',
            field=models.ImageField(null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='rev1',
            field=models.ImageField(null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='rev2',
            field=models.ImageField(null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='rev3',
            field=models.ImageField(null=True, upload_to='settings/'),
        ),
    ]
